spring.application.name=routeCheckpoint
spring.datasource.url=jdbc:mysql://localhost:3306/rutaTuristica?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=validate
!spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
!spring.jpa.show-sql = false
logging.level.org.hibernate.orm.connections.pooling=warn
logging.level.org.hibernate.SQL=warn
logging.level.org.hibernate.transaction=warn

openrouteservice.api.key=5b3ce3597851110001cf624816fa043269fd45c4b61b7dd4b7a99b96

